### ISSUE TITLE
Datos en los views y registrar usuario!

### ISSUE THREAD

**Issue by danielzelayadev** [Kodo-no-Akatsuki/Vacation-System#1]
Necesitamos volver a mostrar los datos en los views y mandar a llamar el registrar usuario desde el
html!

***Esto podria no funcionar a la primera, cualquier cosa notificar aqui

**Comment by AleKiller21** [comment]
Tambien tenemos que tener listo los formularios de roles y permisos.

**Comment by KelviNosse** [comment]
Ya estan conectados los datos de usuario con el html, hace falta registrar el usuario, un poquito de backend ahi.

**Comment by danielzelayadev** [comment]
Ya? Macizo! Lograste volver a llamar lo de registrar usuario? Creo que solo eso faltaba para cerrar este issue

**Comment by AleKiller21** [comment]
Man, pero lo corriste para ver si aparecian?

**Comment by KelviNosse** [comment]
Es que en la version que yo tengo, no tenia eso de registrar usuario, solamente en la version de alejandro, asi que por eso no lo he podido arreglar, lo demas si ya esta listo

**Comment by AleKiller21** [comment]
Lo de registrar (View y controller) ya esta en el repo

**Comment by danielzelayadev** [comment]
Mira lo que tenes que hacer es clonar el repo primero y ahi efectua los cambios que tenias que hacer con el html. Recorda que el pull-request sera al develop branch... Suerte!

**Comment by danielzelayadev** [comment]
Y solo porque mejor prevenir que lamentar repetire.. Hacelo en una branch basada del develop!

**Comment by KelviNosse** [comment]
Ok, perfecto, pero donde alejandro es que le das la instruccion al controller que llame la funcion esa de registrar una vez que el boton de guardar es apretado? lol

**Comment by danielzelayadev** [comment]
Yo tampoco se como es eso😕

**Comment by KelviNosse** [comment]
Es que si, ahi no hay un @ViewData.Model para hacer

**Comment by danielzelayadev** [comment]
Cuando Ale lea nos dira

**Comment by AleKiller21** [comment]
Estoy pensando

**Comment by danielzelayadev** [comment]
Thinkin....

**Comment by AleKiller21** [comment]
Eso lo habiamos hecho como el view de Login

**Comment by KelviNosse** [comment]
siiii, asi como el login, como lo haces en el register?

**Comment by AleKiller21** [comment]
Estoy probando algo, ya les digo

**Comment by KelviNosse** [comment]
Lograstes?

**Comment by AleKiller21** [comment]
Hay un error que no solucionamos ayer con respecto a la creacion de usuarios

**Comment by danielzelayadev** [comment]
Que paja... El que?

**Comment by AleKiller21** [comment]
En el html se nos olvido hacer lo que Daniel habia hecho aquel dia en PapaRotti. Lo de reflection al momento de escribir el "name" y "id"

**Comment by danielzelayadev** [comment]
Ponelo como otro issue sino tiene que ver con este

**Comment by danielzelayadev** [comment]
Uy no recuerdo eso

**Comment by danielzelayadev** [comment]
AHHHH YA! Si es el problema de cuando el modelo era un Empleado verdad?

**Comment by danielzelayadev** [comment]
Funciono eso? No me acuerdo si funciono cuando le puse "Model.User.email"

**Comment by KelviNosse** [comment]
What, daniel en que momento tocaste html?

**Comment by danielzelayadev** [comment]
En paparotti pero ni yo me acordaba

**Comment by KelviNosse** [comment]
Estoy confused, les parece si hago el pull request con lo que tengo, lo clonan, hacen el otro issue, otro pull request y lo solucionan?

**Comment by AleKiller21** [comment]
Kelvin, habla en el otro issue jaja

**Comment by danielzelayadev** [comment]
Kelvin eso que dijiste! Mele iste la mente. Hacelo porfa

**Comment by danielzelayadev** [comment]
Cuando hayamos actualizado tus cambios voy a hacer el fix del otro issue

**Comment by danielzelayadev** [comment]
Kelvin hacete el pull-request!

**Comment by KelviNosse** [comment]
Creo que tendremos que hacer rebase o cherry picking porque al momento de querer hacer pull request me sale develop-design and develop are entirely different commit histories.
