### ISSUE TITLE
Recordatorio de poner los datos en el profile de nuevo!

### ISSUE THREAD

**Issue by danielzelayadev** [Kodo-no-Akatsuki/Vacation-System#17]
@KelviNosse -sama yo te elijo!

**Comment by KelviNosse** [comment]
Eso lo pondre una vez tengamos todo los datos bien estructurados y vinculados con las tablas totalmente

**Comment by danielzelayadev** [comment]
Dale no hay pedo😄 este issue no tiene due date😉

**Comment by KelviNosse** [comment]
El due date es la entrega final lol

**Comment by danielzelayadev** [comment]
Tecnicamente si😁

**Comment by danielzelayadev** [comment]
@KelviNosse trata de hacer esto ahorita porfa! No creo que te tome casi nada

**Comment by danielzelayadev** [comment]
@KelviNosse disculpa esto no! me equivoque

**Comment by danielzelayadev** [comment]
@KelviNosse  Ignoralo vos ya terminaste tu trabajo por hoy :smile:
