### ISSUE TITLE
Bug al crear usuarios

### ISSUE THREAD

**Issue by AleKiller21** [Kodo-no-Akatsuki/Vacation-System#2]
Como le estamos mandando un model de tipo Empleado al View, entonces no podemos simplemente poner en los "id" y "name" de los textboxes del View "PrimerNombre" por ejemplo. Daniel tiene que hacer lo que hizo el viernes que era el tema de reflection para que funcione.

**Comment by danielzelayadev** [comment]
Ale al final funciono eso?

**Comment by danielzelayadev** [comment]
No me acuerdo

**Comment by AleKiller21** [comment]
Yo recuerdo que si

**Comment by AleKiller21** [comment]
Bueno, pero antes de eso hice unos ligeros cambios. Solo una linea de codigo, no vale la pena subirlo

**Comment by AleKiller21** [comment]
```
    [HttpPost]
    public string Register(Empleado emp)
    {
        ServiceClient service = new ServiceClient();

        service.CreateUser(emp);

        service.Close();

        return "Se ha creado el usuario con exito";
    }
```

**Comment by danielzelayadev** [comment]
Ya veo

**Comment by AleKiller21** [comment]
Solo hagan eso en el AccountPageController

Cambiar el nombre a register y agregar el [HttpPost] arriba

**Comment by danielzelayadev** [comment]
Ok poneme de asignado

**Comment by AleKiller21** [comment]
Solo andate dentro del BeginForm en el html del Register View, y en los "id" y "Name" poneles la manera correcta de acceder acada atributo: Empleado->Usuario->PrimerNombre, ejemplo

**Comment by danielzelayadev** [comment]
Roger that

**Comment by KelviNosse** [comment]
Perfecto, ajustare ese cambio alejandro, luego hago pull request?

**Comment by danielzy95** [comment]
Alto quien lo va a hacer vos y yo Kelvin?

**Comment by AleKiller21** [comment]
Ok

**Comment by AleKiller21** [comment]
Hacen ese cambio que mande ustedes o mejor hago pull request yo?

**Comment by danielzy95** [comment]
Si Kelvin lo hara entonces quitame de asignado y ponelo a él.

**Comment by danielzy95** [comment]
Lo hace el del cambio

**Comment by danielzy95** [comment]
El pull request lo manda el que tiene cambios

**Comment by AleKiller21** [comment]
No, Kelvin no lo hara

**Comment by danielzy95** [comment]
Y los cambios los hace el asignado

**Comment by AleKiller21** [comment]
Entonces quien hace el reflection?

**Comment by AleKiller21** [comment]
Kelvin decia que iba a hacer el cambio que habia mandado por aqui

**Comment by danielzy95** [comment]
Ah bueno entonces yo. Kelvin vos resolve el otro issue que te asigne, yo hare este que Ale me asigno y asi trabajaremos con todosl os issues futuros

**Comment by AleKiller21** [comment]
Bueno, solo cambien el nombre del action en el AccountPageController y agreguen [HttpPost] arriba de el, tal y como se los mande por aqui

**Comment by danielzy95** [comment]
Yo lo hare. Respetemos al asignado de cada issue, ya que para eso esta

**Comment by AleKiller21** [comment]
Dale, hacelo vos. Pero recuerden hacer ese cambio que les dije. Sin ello entonces nunca se llamaria al action que inicia el proceso de creacion de usuario.

**Comment by danielzy95** [comment]
Si a eso me refiero, todo este issue yo lo resuelvo

**Comment by AleKiller21** [comment]
ok

**Comment by KelviNosse** [comment]
hey, que paso? dije que yo haria pull request lol, hice una branch develop-design ahi esta lo que cambie

**Comment by danielzy95** [comment]
Sip eso esta buen pero corresponde al otro issue

**Comment by danielzy95** [comment]
Alla yo te conteste que eso era justo lo que ocupaba para poder resolver este issue

**Comment by KelviNosse** [comment]
Bueno, entonces clonate ese arreglalo y hace el pull request para ponerlo en el develop, ahi podes pushear en mi branch que cree, para no saturar haciendo otra

**Comment by danielzy95** [comment]
Wat? No mira, vos te hiciste unos cambios ahorita verdad que son los del otro issue, o al menos asi te correspondia, despues de otro tenias que hacer pull request, no me he fijado si ya la hiciste y despues de evaluartelo te hacias el merge a develop. De ahi venia yohacia un pull de develop y creaba la branch para esye issue, lo arregabla, subia, pull request y merge y con eso resolviamos los dos issues

**Comment by AleKiller21** [comment]
kelvin

**Comment by KelviNosse** [comment]
lol yo decia eso para ahorrar tiempo lol, pero bueno hare el pull request entonces

**Comment by AleKiller21** [comment]
Antes de que hagas el pull request, agrega esto al mero inicio del view de Profile:

@model Vacation_System.ServiceReference.Empleado

**Comment by danielzy95** [comment]
Si te hiciste los cambios para arreglar este issue tambien entonces ya hay que cerrar los issues y continiamos con lo demas

**Comment by danielzy95** [comment]
ALTOOO

**Comment by danielzy95** [comment]
Que pijin, no mezclen los issues

**Comment by danielzy95** [comment]
Ok solo para aclarar, todo issue corresponde a su asignado y todo problema que se postee aqui toca al asignado arreglar. Todas las cosas que se han posteado aqui las tengo que hacer yo. Si se quisiera de otra forma solo cambien al asignado y ya. Pero es para mantener el orden, En cuanto al otro issue, no pongan nada que tenga que ver con esa u otra issue aqui. Aqui solo va lo que tiene que ver con eso y no se olvide que el otro issue aun no se ha cerrado! Mientras siga abierta sigue el debate y los comentatios en el issue! El que abre el issue tiene que cerrarla pq el sabra si ya se arreglo el problema que encontro

**Comment by danielzelayadev** [comment]
Encargandome de este issue ahorita!

**Comment by danielzelayadev** [comment]
Una pregunta, solo deberia de cambiar el valor del atributo 'name' o 'id' y 'placeholder' tambien?

**Comment by AleKiller21** [comment]
Solo "name" y "id"

**Comment by danielzelayadev** [comment]
Dale gracias pibe!

**Comment by danielzelayadev** [comment]
LOL man hasta ahorita me fijo que ya lo habias dicho como 2 veces! Leere este thread de vuelta, es que  estaba borrando comentarios basura

**Comment by AleKiller21** [comment]
jaja dale

**Comment by danielzelayadev** [comment]
No recuerdo haber visto un campo en User llamado "datepicker"... Que es eso?

**Comment by AleKiller21** [comment]
Perame

**Comment by AleKiller21** [comment]
Si, es que Kelvin ocupaba que en el html se llamara datepicker por algo que tenia que ver con el js

**Comment by AleKiller21** [comment]
Entonces le cambiamos el nombre de FechaIngreso en el UserMirror a datepicker, asi no iba haber problemas

**Comment by AleKiller21** [comment]
Solo cambian el nombre de FechaIngreso a datepicker

**Comment by danielzelayadev** [comment]
ya veo...

**Comment by danielzelayadev** [comment]
Pues ahorita voy a correr un test.. A ver

**Comment by AleKiller21** [comment]
Dale

**Comment by AleKiller21** [comment]
Ya sabes como chequear la base de datos?

**Comment by AleKiller21** [comment]
MySQL Workbench o la pagina que nos dio Camilo

**Comment by danielzelayadev** [comment]
Sip

**Comment by danielzelayadev** [comment]
Pues hice la prueba y al guardar me tiro null pointer

**Comment by danielzelayadev** [comment]
![image](https://cloud.githubusercontent.com/assets/7264984/9431979/4ad10666-49d8-11e5-8895-b1dd07b5fbd7.png)

**Comment by AleKiller21** [comment]
Aqui tambien ocupamos a Kelvin

**Comment by danielzelayadev** [comment]
Estoy haciend push con cada commit por si quieren ver mis cambios y me avisan. Hasta ahora mis cambios solo son en Register.cshtml

**Comment by danielzelayadev** [comment]
user-create-fix se llama el branch

**Comment by AleKiller21** [comment]
![capture](https://cloud.githubusercontent.com/assets/7534065/9432016/e6079c62-49d8-11e5-8146-7585f2570972.PNG)
Kelvin, hay forma de ponerle id y name a este segmento de html?

**Comment by danielzelayadev** [comment]
Yo quisiera saber exactamente como se hace para que los datos de los inputs lleguen a un objeto de C#

**Comment by AleKiller21** [comment]
Model Binding. Dentro del beginForm se establecen, a traves del html, los campos donde se ingresaran datos y se les asigna en su id y name el mismo nombre de los atributos en el modelo enlazado que queremos que se inicialicen al momento de llenar esos campos.

**Comment by AleKiller21** [comment]
Al final hay in HTML tag que dice type = "input". Eso genera un POST request el cual regresa al controller donde fue llamado el view y busca al action con el mismo nombre pero que reciba POST request. Ese action tendra de parametron el modelo enlazado con el View y asi se inicializaran los atributos de ese modelo.

**Comment by danielzelayadev** [comment]
Ok voy a look into it y ver si se me ocurre algo

**Comment by AleKiller21** [comment]
Yo pienso que tira null porque en la foto que mande no hay ninguna parte que tenga id o name para que uno de esos dos valores se ingresen a la lista de Departamento del modelo Empleado.

**Comment by AleKiller21** [comment]
Habria que ver de alguna forma de agregarlos a la lista.

**Comment by danielzelayadev** [comment]
Igual, igual pero voy a investigar que ondas

**Comment by AleKiller21** [comment]
Ok

**Comment by AleKiller21** [comment]
Kelvin, manifiestate!

**Comment by danielzelayadev** [comment]
Ok, me parece que acabo de descubrir algo

**Comment by AleKiller21** [comment]
Bien

**Comment by danielzelayadev** [comment]
Correre un pequeno test ahorita y luego hago el push

**Comment by AleKiller21** [comment]
Dale

**Comment by KelviNosse** [comment]
Kusso, hasta ahorita veo, lol eso del combobox la verdad no he probado, pero creo que a los <option les podes poner un id, intenta, si no vamos a probar con otro metodo

**Comment by danielzelayadev** [comment]
Gran descubrimiento ahorita! El User.PropiedadXDelEmpleado funciona! El null lo tira solo porque en realidad no estamos salvando el depto

**Comment by AleKiller21** [comment]
No lo estamos agregando a la lista?

**Comment by danielzelayadev** [comment]
Eso si, la fecha no se guarda con datepicker

**Comment by AleKiller21** [comment]
Hay que probar de otra forma con la fecha. El nullPointerException era porque no se estaba guardando el departamento en la lista de Empleado?

**Comment by KelviNosse** [comment]
la fecha esta en formato yyyy/mm/dd, a que se refieren con que no se guarda?

**Comment by AleKiller21** [comment]
Es que Daniel tiene que cambiarle el nombre para que se pueda guardar, creo que a User.datepicker

**Comment by KelviNosse** [comment]
A el datepicker le pueden cambiar el nombre, solo que en el js del cshtml, tienen que cambiarlo tambien.

**Comment by danielzelayadev** [comment]
Voy a volver a probar eso pq la primera vez no me fije y le quite el User. a datepicker solo se lo deje a todo lo demas

**Comment by danielzelayadev** [comment]
Hey por cierto lo de guardar depto. y roles que fuera de este issue. Ya que estan como combo boxes y tienen que ser check boxes

**Comment by danielzelayadev** [comment]
Te lo deje como tarjetita en Trello Kelvin-kun

**Comment by danielzelayadev** [comment]
Hare que guarde la fecha  y de ahi cerramos este issue

**Comment by AleKiller21** [comment]
Ok

**Comment by danielzelayadev** [comment]
HEY!!! Hijole acabo de recordar que si le pongo User.datepicker no sale el calendario!

**Comment by danielzelayadev** [comment]
Que hacemos ahi...Encrucijada

**Comment by AleKiller21** [comment]
Cambiale el nombre al js como dijo Kelvin. Me imagino que habria que nombrarlo User.datepicker

**Comment by danielzelayadev** [comment]
Ah bien, no me fije en ese comment... Voy

**Comment by KelviNosse** [comment]
sii tenes que ser bien cuidadoso ahi, solamente hay una funcion que se llama datepicker();
que esa no la podes cambiar. Si no mal recuerdo era 

``` javascript
$(#datepicker).datepicker(); 
```

La funcion esa si no la cambies, solo el id nada mas.

**Comment by danielzelayadev** [comment]
El que tiene # verdad?

**Comment by danielzelayadev** [comment]
Ohh no

**Comment by danielzelayadev** [comment]
LOL Perate si lo cambie HAHA.

**Comment by KelviNosse** [comment]
ahaha bueno, sii el id simbolizado por #

**Comment by danielzelayadev** [comment]
Curiosamente me tira EntityException al momento del login en el web service pero no tiene sentido porque nada ha cambiado, incluso me asegure que el objeto no estuviera nulo y etc. Siento que cuando tirara esa excepcion es por la conexion... Asaber

**Comment by KelviNosse** [comment]
What? que extraño eso, no deberia tirar nada, es un simple id

**Comment by AleKiller21** [comment]
Ese exception te lo tiro hasta despues de haber cambiado el id del datepicker?

**Comment by danielzelayadev** [comment]
No e por cambios

**Comment by danielzelayadev** [comment]
Es por la conexion, ya no me la tiro

**Comment by AleKiller21** [comment]
Ya veo. Se arreglo solo

**Comment by danielzelayadev** [comment]
Se tarda en conectar y cuando no logra conectar te tira exception. Pura cerotada

**Comment by danielzelayadev** [comment]
Cuando si conecta agarra rapido

**Comment by danielzelayadev** [comment]
En fin, ya pude probar si cambiando el id a User.datepicker y no sale :/ el calendario

**Comment by KelviNosse** [comment]
umm ya veo, genial entonces, a cuanto estamos de arreglar el issue?

**Comment by danielzelayadev** [comment]
Genial??? HAHA No me sale el calendario y no podemos guardar el dato! Es lo unico que falta

**Comment by danielzelayadev** [comment]
Kelvin tal vez vos lo podes arreglar mejor que yo

**Comment by danielzelayadev** [comment]
Te lo paso?

**Comment by KelviNosse** [comment]
Ha de ser el server de camilo, tal vez por eso

**Comment by danielzelayadev** [comment]
El entity exception si ha de ser por el server de Camilo, mas que fijo

**Comment by KelviNosse** [comment]
quizas si, pero ahora estoy algo ocupado en el diseño

**Comment by danielzelayadev** [comment]
Pero eso ni modo. Queres quedarte encargado de arreglar esto?

**Comment by danielzelayadev** [comment]
Ahh ya veo

**Comment by danielzelayadev** [comment]
Dejemoslo abierto pues

**Comment by KelviNosse** [comment]
SIi, ya veremos solucionar eso, una vez termine el diseño

**Comment by danielzelayadev** [comment]
Cheque

**Comment by AleKiller21** [comment]
Entonces, cual es el siguiente paso?

**Comment by KelviNosse** [comment]
lol, igual me asignaste

**Comment by KelviNosse** [comment]
Lo que se necesita es ver la forma en como implementar los forms de roles y deptos a nivel backend, conectandolo a la base de datos con sus respectivas tablas

**Comment by danielzelayadev** [comment]
Si pero para el rato no tenes que resolver el issue ahorita, solo pense que serias el mas indicado

**Comment by danielzelayadev** [comment]
Ya dejen este issue por ahorita
