### ISSUE TITLE
No Aparece el DatePicker en Chrome

### ISSUE THREAD

**Issue by danielzelayadev** [Kodo-no-Akatsuki/Vacation-System#4]
Podria solo ser un error de Capa 8... pero por ahora no me sale el date picker

**Comment by AleKiller21** [comment]
Dejame ver

**Comment by AleKiller21** [comment]
Como es el reflection que le pusiste?

**Comment by danielzelayadev** [comment]
User.datepicker

**Comment by AleKiller21** [comment]
Creo que es porque al aplicarle el reflection, ya no va a estar haciendo referencia al js que se llamaba datepicker

**Comment by AleKiller21** [comment]
Recuerdo que Kelvin dijo que tenia que quedarse como datepicker. Necesitamos a Kelvin aqui en esta discucion

**Comment by danielzelayadev** [comment]
Si, @KelviNosse manifiestate!

**Comment by danielzelayadev** [comment]
Puedo quitar el User.datepicker pero entonces donde se guardaria la fecha de ingreso...

**Comment by danielzelayadev** [comment]
Lo quitare solo para resolver este issue y en el otro discutimos el resto

**Comment by AleKiller21** [comment]
Kelvin!

**Comment by danielzelayadev** [comment]
Listo, fixed!
