### ISSUE TITLE
Bugs en el View de Departments

### ISSUE THREAD

**Issue by AleKiller21** [Kodo-no-Akatsuki/Vacation-System#7]
Hay que cambiar unas lineas de HTML que tratan de acceder al atributo Usuario del modelo Empleado. Al haber cambiado el modelo por DepartmentMirror, estas lineas haran que truene la aplicacion.

**Comment by AleKiller21** [comment]
Una cosa mas, seria bueno aprovechar ahorita para que hagas la vinculacion. Asi lo puedo probar cuando implemente mi parte.

**Comment by danielzelayadev** [comment]
Otro issue !!! :(!!!

**Comment by AleKiller21** [comment]
Estamos aprendiendo a usar Github

**Comment by AleKiller21** [comment]
Kelvin, solo quita las lineas donde muestra datos del usuario. Tambien si me pudieras indicar a cuales elementos tengo que cambiarle el id y name.

**Comment by KelviNosse** [comment]
Umm ale, ese view de departments todavia no esta terminado, asi que todavia no te preocupes por el id y name, pero si quitare la linea en el proximo pull request, que tambien estare actualizando el diseño aun mas

**Comment by AleKiller21** [comment]
Dale, no hay problema entonces

**Comment by AleKiller21** [comment]
Pero hasta que la termines es que podre terminar la implementacion de agregar departamentos

**Comment by AleKiller21** [comment]
Por mientras, dejemos el issue abierto hasta que ya hayamos terminado con los departments.

**Comment by KelviNosse** [comment]
vale, en eso estoy

**Comment by KelviNosse** [comment]
por mientras pueden ir estructurando los roles

**Comment by AleKiller21** [comment]
Cheque

**Comment by danielzelayadev** [comment]
Se resolvio ya este issue? @AleKiller21
